Add node-setup doc
OAK-Foundation/OAK-blockchain pull request #14
Opened 2021-06-01 07:05 UTC by imstar15

2021-06-01 07:13 UTC, chrisli30 requested changes

2021-06-01 07:13 UTC, chrisli30 commented on docs/node-setup.md
> +#### Options:
这里不是让你把--help里面的内容复制过来，这些option中哪些是你配置过或使用过的？

--dev 的意思等同于 --chain development?

development的chain_spec里面又设置了什么样的参数？

我的需求是解释chain_spec里面你用到过的那些参数

2021-06-01 07:14 UTC, chrisli30 requested changes

2021-06-01 07:14 UTC, chrisli30 commented on docs/node-setup.md
> +docker run -d --name <container_name> imstar15/oak-testnet:latest --name <node_name>
imstar15/oak-testnet 是用这个镜像？

2021-06-01 08:14 UTC, imstar15 commented on docs/node-setup.md
> +#### Options:
development里面都是些substrate默认的配置，我在文档里加上解释了。

2021-06-01 08:20 UTC, imstar15 commented on docs/node-setup.md
> +#### Options:
有些参数是不能在命令行里配置的

2021-06-01 08:23 UTC, imstar15 commented on docs/node-setup.md
> +#### Options:
其实我是觉得没必要解释很详细，把这个要解释透，可以出一篇修改substrate启动配置项的教程了，它本身就有一定的复杂性的。

2021-06-01 08:26 UTC, imstar15 commented on docs/node-setup.md
> +#### Options:
想要去系统的了解就是需要去学习substrate了。
 
 可以参考substrate的文档和凯超老师的这篇文章：
https://zhuanlan.zhihu.com/p/161293660

2021-06-01 08:29 UTC, imstar15 commented on docs/node-setup.md
> +docker run -d --name <container_name> imstar15/oak-testnet:latest --name <node_name>
Fixed

2021-06-02 01:19 UTC, chrisli30 approved these changes
行，这样目前应该够了，这个issue的任务是写到oak-doc里面，这些内容你要搬过去，跑一下看看效果，目标文件是 docs/node-setup.md

2021-06-02 01:19 UTC, chrisli30 commented on docs/node-setup.md
> +#### Options:
okay

2021-06-02 02:24 UTC, merged