Fix test coverage.
OAK-Foundation/OAK-blockchain pull request #163
Opened 2022-05-26 14:28 UTC by imstar15

1. grcov generate the coverage file: lcov.info.

Ignore target/*, **test.rs

```
grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" --ignore "target/*" --ignore "**tests.rs" -o lcov.info
```

doc: https://github.com/mozilla/grcov/blob/master/README.md

1. Fix coverage

```
rust-covfix -o lcov_correct.info lcov.info
```

doc: https://crates.io/crates/rust-covfix 

Result:
https://bugmoon.test.s3-website-us-east-1.amazonaws.com/coverage

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/16951509/170508522-1112a7c6-9f57-47c0-b7eb-d840e5013ac8.png">

The test code in lib.rs will not be count.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/16951509/170507401-ce1976ab-a44f-419f-bab2-5f2141334475.png">

2022-05-31 19:04 UTC, atomaka requested changes
The check is failing because of a typo I noted.

2022-05-31 19:04 UTC, atomaka commented on .github/workflows/check.yml
> +          sh ./maintain/test-coverage/test-coverage.sh
Caller is here.  Probably intended

```suggestion
          sh ./.maintain/test-coverage/test-coverage.sh
```

2022-06-01 03:20 UTC, imstar15 commented on .github/workflows/check.yml
> +          sh ./maintain/test-coverage/test-coverage.sh
Sorry, My mistake. Fixed.

2022-06-01 14:51 UTC, atomaka approved these changes
Looks good. Failing from memory issues now.

2022-06-02 03:07 UTC, merged