Adding neumann chain_spec; unverified if this is functional
OAK-Foundation/OAK-blockchain pull request #35
Opened 2021-12-07 02:24 UTC by irsal

2021-12-08 01:03 UTC, irsal commented on node/src/chain_spec.rs
> +				vec![
remove default accounts

2021-12-09 01:14 UTC, irsal commented
Seems fine to keep the .json https://raw.githubusercontent.com/AcalaNetwork/Acala/master/resources/karura-dist.json

2021-12-09 06:32 UTC, irsal commented
Open questions / thoughts:

 - polkadot-launch/config.json might not be useful (I have not isolated and tested removing this...though i assume it's not since we're NOT using the `polkadot-launch` tool
 - "chainType": "Local" vs "Live" vs something else (What does staging look like?)
 - how does --chain=neumann-staging tie to `chainType`
 - when i set  "chainType": "Live", all of the seed accounts go away
 - chaintype: Local, all of the seed accounts come back, what config do we need to make sure that "Live" seed accounts are not Alice, etc.

2021-12-09 22:03 UTC, irsal commented
Woof, we had the wrong rebase config. We need to default to squash.

2021-12-09 22:07 UTC, irsal commented on README.md
> +
This README section is your friend. OnFinality docs are buggy/awful.

2021-12-10 01:30 UTC, chrisli30 approved these changes

2021-12-10 01:32 UTC, chrisli30 requested changes
This PR is not done yet. Need to rebase.

2021-12-10 04:21 UTC, imstar15 commented
I rebase this branch.

2021-12-22 05:21 UTC, chrisli30 approved these changes
Looks good to me, but let’s get more feedback from others.

2021-12-22 05:22 UTC, chrisli30 commented
> Looks good to me, but let’s get more feedback from others.

We can also check this in, deploy with the Docker image, and give it a try.

2021-12-23 22:38 UTC, merged