Add Dockerfile for neumann
OAK-Foundation/OAK-blockchain pull request #36
Opened 2021-12-07 03:26 UTC by imstar15

2021-12-07 03:27 UTC, irsal approved these changes
👍

2021-12-07 21:07 UTC, irsal commented on docker/testnet/Dockerfile
> +FROM ubuntu:20.04
we don't really need testnet anymore, but this structure is still useful for when we have multiple chains (turing, oak, etc)

2021-12-07 23:34 UTC, irsal commented on docker/neumann/Dockerfile
> +ENTRYPOINT ["./neumann-collator", "-d", "data/node"]
```
./target/release/neumann-collator --collator --alice --force-authoring --tmp --port 40335 --ws-port 9946 -- --execution wasm --chain resources/rococo-local.json --port 30335
```

See README: https://github.com/OAK-Foundation/OAK-blockchain#launch-the-parachain

2021-12-07 23:34 UTC, irsal requested changes
i think there's an issue w/ the way we're building the docker image

2021-12-08 17:47 UTC, chrisli30 reviewed
The problem of "Version check failed" has not been resolved. It is related to the protocol definition of OnFinality.

I assume the PR is not done. If yes, let’s add a [WIP] to the title, so reviewers know it’s a Work-in-progress.

2021-12-09 01:06 UTC, irsal approved these changes
thanks for removing the old code

2021-12-09 01:16 UTC, imstar15 commented on docker/neumann/Dockerfile
> +RUN apt-get update && apt-get install -y curl && \
Install curl to request rotateKeys via RPC in docker

2021-12-09 01:16 UTC, imstar15 commented on docker/neumann/Dockerfile
> +  find /usr/bin/* /usr/sbin/* | grep -v curl | xargs rm
Delete binarys except curl

2021-12-09 01:19 UTC, imstar15 commented on docker/neumann/Dockerfile
> +EXPOSE 30333 30334 9933 9944 9615
默认暴露了这些端口，如果一台机器用这个image运行多个进程，端口会冲突，需要用-p参数去重新映射。

2021-12-09 01:22 UTC, imstar15 commented on docker/neumann/Dockerfile
> +  find /usr/bin/* /usr/sbin/* | grep -v curl | xargs rm
But this is safer. The mirror image of Moonbeam and Polkadot is the same.

2021-12-09 01:25 UTC, merged