Remove schedule native transfer
OAK-Foundation/OAK-blockchain pull request #377
Opened 2023-06-29 10:58 UTC by v9n

This task is obsolute by schedule_dynamic_dispatch_tasks and passing the Balance extrinsic

2023-06-30 16:48 UTC, chrisli30 commented on pallets/automation-time/src/benchmarking.rs
> +		let time1 = 10800;
remember to change it back to `executionTime`

2023-06-30 23:51 UTC, chrisli30 approved these changes
LGTM

2023-06-30 23:51 UTC, chrisli30 commented on pallets/automation-time/src/tests.rs
> +// 20_000: to move a single time slot to missed tasks (shift_missed_tasks)
Yeah these comments and numbers are clear

2023-07-01 09:38 UTC, imstar15 requested changes
<img width="859" alt="image" src="https://github.com/OAK-Foundation/OAK-blockchain/assets/16951509/cf516ae4-843b-4642-9c53-3fdf5f870b79">

Please run the commands and fix to pass the two checks.

rustfmt
```
cargo fmt -- --check
```

Test

```
cargo test --workspace --all-features
```

2023-07-05 17:29 UTC, chrisli30 reviewed
Looks good to me overall, but I have got several comments.

2023-07-05 17:29 UTC, chrisli30 commented on pallets/automation-time/src/tests.rs
> +		let bob = AccountId32::new(BOB);
Let’s not use name such as bob for a wallet, instead use a functional name. For example, if bob is the creator of the task, call it `creator` or `signer`.

This rule should apply to all tests, and we can update them whenever we work on other tests. Let me know what you think.

2023-07-05 17:29 UTC, chrisli30 commented on pallets/automation-time/src/tests.rs
> +		let w = AutomationTime::trigger_tasks(Weight::from_ref_time(900_000_000));
Let’s not use a name with a single letter like this. I assume this variable is never used below but still, please think of a meaningful name for this variable.

2023-07-05 17:29 UTC, chrisli30 commented on pallets/automation-time/src/mock.rs
> +	pub const MaxWeightPerSlot: u128 = 700_000_000;
Could you comment here, on the reason to 10x this value?

2023-07-07 02:05 UTC, imstar15 approved these changes
Looks good to me!

2023-07-07 17:00 UTC, merged