Delete session keys.
OAK-Foundation/OAK-blockchain pull request #38
Opened 2021-12-09 03:09 UTC by imstar15

2021-12-09 03:58 UTC, irsal commented
@imstar15 - what's scripts/session_keys/.gitkeep ?

2021-12-09 04:12 UTC, imstar15 commented
> @imstar15 - what's scripts/session_keys/.gitkeep ?

A GITKEEP file is an empty file that Git users create so that a Git repository preserves an otherwise empty project directory. By convention, empty directories that contain no files are not committed to Git repositories. However, a single GITKEEP file in a directory causes Git to preserve the directory in the repository.

2021-12-10 01:46 UTC, chrisli30 requested changes
Yes, let’s remove the .gitkeep, and this folder completely.

2021-12-10 02:46 UTC, chrisli30 approved these changes

2021-12-10 02:47 UTC, merged