Do not run missed tasks
OAK-Foundation/OAK-blockchain pull request #75
Opened 2022-02-11 23:08 UTC by rhuttman

2022-02-12 22:36 UTC, justinzhou93 requested changes
couple of questions

2022-02-12 23:13 UTC, rhuttman commented on pallets/automation-time/src/lib.rs
> +			if weight_left >= 60_000 {
I want to ensure I can complete 1 task before diving in

2022-02-12 23:16 UTC, rhuttman commented on pallets/automation-time/src/lib.rs
> +				let missed_queue = Self::get_missed_queue();
a task will either be run or handled by the missed queue (sending an event to notify that we missed it). Once of those two things must happen.

This setup will only work for minutes. There will need to be extra logic when different time intervals are added. I would think we still have 1 missed queue but 4 task queue and 4 trigger maps

2022-02-12 23:17 UTC, rhuttman commented on pallets/automation-time/src/tests.rs
> +		assert_ne!(AutomationTime::get_task(task_id2), None);
This is not checking the queue. This is checking the task map to see if the task is still in there

2022-02-12 23:18 UTC, rhuttman commented on pallets/automation-time/src/tests.rs
> +fn trigger_tasks_completes_all_missed_tasks() {
If we just complete some of the missed tasks? I can add it but its the same as the some scheduled ones

2022-02-14 18:05 UTC, justinzhou93 approved these changes

2022-02-15 05:11 UTC, merged